# Generated by Django 2.0.6 on 2019-03-22 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_file', models.FileField(blank=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'AnswerFile',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ImageField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Percentile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composite_score', models.CharField(blank=True, max_length=255)),
                ('percentile', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PercentileFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentile_file', models.FileField(blank=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'PercentileFile',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.CharField(blank=True, max_length=255)),
                ('answer_key', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TestName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TestSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.CharField(blank=True, max_length=255)),
                ('section_type', models.CharField(blank=True, max_length=255)),
                ('test_name_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scan_score.TestName')),
            ],
        ),
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='testname',
            name='test_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scan_score.TestType'),
        ),
        migrations.AddField(
            model_name='question',
            name='test_section_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scan_score.TestSection'),
        ),
    ]
